## Write a program that will find all numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a list

In [14]:
rang = range(2000, 3201)
lis1 = []
for num in rang:
  if num % 7 == 0 and num % 5 != 0:
    lis1.append(num)

In [35]:
print(lis1)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


# Write a program that can compute the factorial of a given number. (The factorial of n is the product of all positive integers less than or equal to n.) For example: For factorial(5)= 5 x 4 x 3 x 2 x 1 the result is 120 (i.e. factorial (0)=1).

In [61]:
def factorial(n):
    if n<1:
        print('Error')
    elif n==1:
        return 1
    else:
         (n* factorial(n-1))

In [64]:
factorial(7)

5040

# With a given integer number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included). Then, the program should print the dictionary. Suppose the following input is supplied to the program: 8 Then, the output should be: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}  

In [47]:
def sqr(a,b):
  dic = {}
  for i in range (a,b):
    dic.update({i:i*i})
  print(dic)

In [65]:
sqr(1,40)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361, 20: 400, 21: 441, 22: 484, 23: 529, 24: 576, 25: 625, 26: 676, 27: 729, 28: 784, 29: 841, 30: 900, 31: 961, 32: 1024, 33: 1089, 34: 1156, 35: 1225, 36: 1296, 37: 1369, 38: 1444, 39: 1521}


# Given a non-empty string and an integral n, return a new string where the char at index n has been removed. The value of n will be a valid index of a char in the original string (i.e. n will be in the range 0..len(str)-1 inclusive). 

missing_char('kitten', 1) → 'ktten'    for example here we remove "i" which is located in the index 1

missing_char('kitten', 0) → 'itten'   here we remove "k" which is in the index 0

missing_char('kitten', 4) → 'kittn'   here we remove "e" which is in the index 4

In [119]:
def remove_char(str,n):
    return str[:n] + str[n+1:] #return the first part of your string +return the last part of your string

In [120]:
remove_char('puppy', 0)

'uppy'

In [121]:
remove_char('puppy', 3)

'pupy'

In [122]:
remove_char('puppy',4)

'pupp'

# Write a NumPy program to convert a NumPy array into a Python list structure.

Expected output: 

Original array elements: [[0 1] [2 3] [4 5]] 

Array to list: [[0, 1], [2, 3], [4, 5]] 
 

Hint: We can use the to_list() function to ensure the conversion.

In [132]:
import numpy as np

In [134]:
y = np.array([[2,5],[4,9]])

In [25]:
data = np.array([[0,1],[2,3],[4, 5]])

In [26]:
type(data)

numpy.ndarray

In [28]:
new_data = data.tolist()

In [151]:
new_data

[[0, 1], [2, 3], [4, 5]]

# Write a NumPy program to compute the covariance matrix of two given arrays. 

Original array1: [0 1 2] 

Original array2: [2 1 0] 

Covariance matrix of the said arrays: [[ 1. -1.] [-1. 1.]]
 

Hint: We can use the np.cov() function to calculate the covariance between these two arrays

In [6]:
import numpy as np

In [7]:
m = np.array([0,1,2])
n = np.array([2,1,0])

In [13]:
print(m)

[0 1 2]


In [14]:
print(n)

[2 1 0]


In [20]:
print("nCovariance matrix:\n",np.cov(m, n))

nCovariance matrix:
 [[ 1. -1.]
 [-1.  1.]]


# Question: Write a program that calculates and prints the value according to the given formula: Q= Square root of [(2 * C * D)/H] 

The following are the fixed values of C and H: C is 50. H is 30. 

D is the variable whose values should be input into your program in a comma-separated sequence. (That means D contains more than value)

Example: Let's assume the following comma-separated input sequence is given to the program: 100,150,180 The output of the program should be 18,22,24 

To further explain this, we will obtain a result for each value of D:  Q1= Square root of [(2 * C * 100)/H] =18, Q2= Square root of [(2 * C * 150)/H] = 22 and Q3 = Square root of [(2 * C * 180)/H]  = 24

Hint: If the output received is in decimal form, it should be rounded off to its nearest value. For example, if the output received is 26.0, it should be printed as 26. In case of input data being supplied to the question, it should be assumed to be a console input. 

In [1]:
c = 50
h = 30
d = []
def root(values):
    for d in values:
        d.append(int(((2*c*d)/h)**0.5))
    return d

In [155]:
root([25, 800, 6])

[9, 51, 4]